# User Management Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  labels:
    app: user-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: user-management-service:latest
        ports:
        - containerPort: 3000
---
# Appointment Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: appointment-service:latest
        ports:
        - containerPort: 3001
---
# Medical Records Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-records-service
  labels:
    app: medical-records-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medical-records-service
  template:
    metadata:
      labels:
        app: medical-records-service
    spec:
      containers:
      - name: medical-records-service
        image: medical-records-service:latest
        ports:
        - containerPort: 3002
