apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: healthcare-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-management-vs
spec:
  hosts:
  - "*"
  gateways:
  - healthcare-gateway
  http:
  - match:
    - uri:
        prefix: /users
    route:
    - destination:
        host: user-management-service
        port:
          number: 3000
